# Generated by Django 4.2.4 on 2023-11-10 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='starts_given',
            new_name='stars_given',
        ),
    ]
