# Generated by Django 4.2.7 on 2023-11-18 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_rename_starts_given_review_stars_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.ImageField(default=datetime.datetime(2023, 11, 18, 17, 11, 33, 885505, tzinfo=datetime.timezone.utc), upload_to='images/'),
            preserve_default=False,
        ),
    ]
