# Generated by Django 4.2.7 on 2023-11-18 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2023, 11, 18, 18, 29, 17, 452493, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
