# Generated by Django 4.2.7 on 2023-11-18 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='slug',
        ),
    ]
